- name: playbook3
  hosts: all
  become: true
  gather_facts: false
  vars:
    user_name: devops
    user_uid: 1500
  tasks:
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ user_name }}"
        uid: "{{ user_uid }}"
        state: present
        create_home: true
        shell: /bin/bash
